done

diff --git a/util/Vagrantfile b/util/Vagrantfile
--- a/util/Vagrantfile
+++ b/util/Vagrantfile
@@ -3,7 +3,7 @@
 
 Vagrant.configure("2") do |config|
   require 'time'
-  
+
   # VM type
   config.vm.box = "ubuntu/xenial64"
 
@@ -27,69 +27,54 @@ Vagrant.configure("2") do |config|
   config.vm.synced_folder "../..", "/RUDOLF"
 
   config.vm.synced_folder ENV['HOME'] + "/.kaggle", "/home/ubuntu/.kaggle", mount_options: ['dmode=700,fmode=600']
-  # config.vm.synced_folder ENV['HOME'] + "/.secrets", "/home/ubuntu/.secrets", mount_options: ['dmode=700,fmode=600']
-
-  config.vm.provision "shell", inline: <<-SHELL
-
-    if ! sudo grep -q "export KAGGLE_CONFIG_DIR='/home/ubuntu/.kaggle'" /etc/profile.d/myvar.sh ; then
-      sudo echo "export KAGGLE_CONFIG_DIR='/home/ubuntu/.kaggle'" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export GOOGLE_APPLICATION_CREDENTIALS='/home/ubuntu/.secrets/service_account.json'" /etc/profile.d/myvar.sh ; then
-      sudo echo "export GOOGLE_APPLICATION_CREDENTIALS='/home/ubuntu/.secrets/service_account.json'" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export VIRTUALENV_ALWAYS_COPY=1" /etc/profile.d/myvar.sh ; then
-      sudo echo "export VIRTUALENV_ALWAYS_COPY=1" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "source /RUDOLF/base/dotfiles/.bashrc-shared-settings" .bashrc ; then
-      sudo echo "source /RUDOLF/base/dotfiles/.bashrc-shared-settings" >> .bashrc
-    fi
-
-
-    if ! sudo grep -q "export CHANGE_MINIKUBE_NONE_USER=true" /etc/profile.d/myvar.sh ; then
-      sudo echo "export CHANGE_MINIKUBE_NONE_USER=true" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export MINIKUBE_WANTUPDATENOTIFICATION=false" /etc/profile.d/myvar.sh ; then
-      sudo echo "export MINIKUBE_WANTUPDATENOTIFICATION=false" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export MINIKUBE_WANTREPORTERRORPROMPT=false" /etc/profile.d/myvar.sh ; then
-      sudo echo "export MINIKUBE_WANTREPORTERRORPROMPT=false" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export MINIKUBE_HOME='/home/vagrant'" /etc/profile.d/myvar.sh ; then
-      sudo echo "export MINIKUBE_HOME='/home/vagrant'" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export KUBECONFIG='/home/vagrant/.kube/config'" /etc/profile.d/myvar.sh ; then
-      sudo echo "export KUBECONFIG='/home/vagrant/.kube/config'" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export MINIKUBE_MEMORY=26000" /etc/profile.d/myvar.sh ; then
-      sudo echo "export MINIKUBE_MEMORY=26000" >> /etc/profile.d/myvar.sh
-    fi
-
-    if ! sudo grep -q "export MINIKUBE_CPU=4" /etc/profile.d/myvar.sh ; then
-      sudo echo "export MINIKUBE_CPU=4" >> /etc/profile.d/myvar.sh
-    fi
-
-  SHELL
+  config.vm.synced_folder ENV['HOME'] + "/.secrets", "/home/ubuntu/.secrets", mount_options: ['dmode=700,fmode=600']
 
   config.vm.provider "virtualbox" do |vb|
-    # Display the VirtualBox GUI when booting the machine
+
+    # Not display the VirtualBox GUI when booting the machine
     vb.gui = false
 
     # Virtualbox name
     vb.name = "developer-box"
 
+    # Give VM 75% system memory & access to all cpu cores on the host with an execution cap of 85%
+    mem_ratio = 0.75
+    cpu_exec_cap = 85
+    host = RbConfig::CONFIG['host_os']
+    
+    if host =~ /darwin/
+
+      cpus = `sysctl -n hw.ncpu`.to_i
+
+      # sysctl returns Bytes and we need to convert to MB
+      mem = `sysctl -n hw.memsize`.to_i / 1024^2 * mem_ratio
+
+    elsif host =~ /linux/
+
+      cpus = `nproc`.to_i
+
+      # meminfo shows KB and we need to convert to MB
+      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 * mem_ratio
+
+    else # Windows folks
+
+      cpus = `wmic cpu get NumberOfCores`.split("\n")[2].to_i
+      mem = (`wmic OS get TotalVisibleMemorySize`.split("\n")[2].to_i / 1024 * mem_ratio).round
+
+    end
+
+    puts "Provisioning VM with host #{host} and #{cpus} CPU's (at #{cpu_exec_cap}%) and #{mem/1024} GB RAM."
+    
     # Customize amount of memeory and cpu
-    vb.customize ["modifyvm", :id, "--memory", "36000", "--cpus", "4", "--ioapic", "on", "--cpuexecutioncap", "100"]
+    #vb.customize ["modifyvm", :id, "--memory", "36000", "--cpus", "4", "--ioapic", "on", "--cpuexecutioncap", "100"]
+    vb.customize ["modifyvm", :id, "--memory", mem, "--cpus", cpus, "--ioapic", "on", "--cpuexecutioncap", cpu_exec_cap]
+    #vb.customize ["modifyvm", :id, "--memory", mem]
+    #vb.customize ["modifyvm", :id, "--cpus", cpus]
+    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", cpu_exec_cap]
 
   end
 
+  # Fix potential issues with timezones and system clock
   offset = ((Time.zone_offset(Time.now.zone) / 60) / 60)
   timezone_suffix = offset >= 0 ? "-#{offset.to_s}" : "+#{offset.to_s}"
   timezone = 'Etc/GMT' + timezone_suffix
@@ -130,37 +115,6 @@ Vagrant.configure("2") do |config|
     # Kaggle
     chmod 600 /home/ubuntu/.secrets/secrets.yaml && \
       chmod 600 /home/ubuntu/.kaggle/kaggle.json
-
-    # https://serverfault.com/questions/918335/best-way-to-run-python-3-7-on-ubuntu-16-04-which-comes-with-python-3-5
-    # Install requirements
-    #sudo apt-get install -y build-essential \
-    #  checkinstall \
-    #  libreadline-gplv2-dev \
-    #  libncursesw5-dev \
-    #  libssl-dev \
-    #  libsqlite3-dev \
-    #  tk-dev \
-    #  libgdbm-dev \
-    #  libc6-dev \
-    #  libbz2-dev \
-    #  zlib1g-dev \
-    #  openssl \
-    #  libffi-dev \
-    #  python3-dev \
-    #  python3-setuptools \
-    #  wget
-
-    # Pull down Python 3.7, build, and install
-    #mkdir /tmp/Python37 && \
-    #  cd /tmp/Python37 && \
-    #  wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz && \
-    #  tar xvf Python-3.7.0.tar.xz && \
-    #  cd /tmp/Python37/Python-3.7.0 && \
-    #  ./configure && \
-    #  sudo make altinstall
-
-    # Tkinter
-    # sudo apt-get install python3-tk -y
     
     # X11
     sudo apt-get install x11-xserver-utils -y
@@ -171,13 +125,56 @@ Vagrant.configure("2") do |config|
     # ansible
     sudo -E apt-add-repository -y ppa:ansible/ansible && \
       sudo apt-get update && \
-      sudo apt-get -y install ansible && \
-      ansible-playbook /projects/base/util/setup/provisioner.yml
+      sudo apt-get -y install ansible
 
-    #config.vm.provision "ansible" do |ansible|
-    #  ansible.verbose = "v"
-    #  ansible.playbook = "/RUDOLF/base/util/setup/provisioner.yml"
-    #end
+    config.vm.provision "ansible" do |ansible|
+      ansible.verbose = "v"
+      ansible.playbook = "/RUDOLF/base/util/setup/provisioner.yml"
+    end
+
+    if ! sudo grep -q "export KAGGLE_CONFIG_DIR='/home/ubuntu/.kaggle'" /etc/profile.d/myvar.sh ; then
+      sudo echo "export KAGGLE_CONFIG_DIR='/home/ubuntu/.kaggle'" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export GOOGLE_APPLICATION_CREDENTIALS='/home/ubuntu/.secrets/service_account.json'" /etc/profile.d/myvar.sh ; then
+      sudo echo "export GOOGLE_APPLICATION_CREDENTIALS='/home/ubuntu/.secrets/service_account.json'" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export VIRTUALENV_ALWAYS_COPY=1" /etc/profile.d/myvar.sh ; then
+      sudo echo "export VIRTUALENV_ALWAYS_COPY=1" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "source /RUDOLF/base/dotfiles/.bashrc-shared-settings" .bashrc ; then
+      sudo echo "source /RUDOLF/base/dotfiles/.bashrc-shared-settings" >> .bashrc
+    fi
+
+    if ! sudo grep -q "export CHANGE_MINIKUBE_NONE_USER=true" /etc/profile.d/myvar.sh ; then
+      sudo echo "export CHANGE_MINIKUBE_NONE_USER=true" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export MINIKUBE_WANTUPDATENOTIFICATION=false" /etc/profile.d/myvar.sh ; then
+      sudo echo "export MINIKUBE_WANTUPDATENOTIFICATION=false" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export MINIKUBE_WANTREPORTERRORPROMPT=false" /etc/profile.d/myvar.sh ; then
+      sudo echo "export MINIKUBE_WANTREPORTERRORPROMPT=false" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export MINIKUBE_HOME='/home/vagrant'" /etc/profile.d/myvar.sh ; then
+      sudo echo "export MINIKUBE_HOME='/home/vagrant'" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export KUBECONFIG='/home/vagrant/.kube/config'" /etc/profile.d/myvar.sh ; then
+      sudo echo "export KUBECONFIG='/home/vagrant/.kube/config'" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export MINIKUBE_MEMORY=26000" /etc/profile.d/myvar.sh ; then
+      sudo echo "export MINIKUBE_MEMORY=26000" >> /etc/profile.d/myvar.sh
+    fi
+
+    if ! sudo grep -q "export MINIKUBE_CPU=4" /etc/profile.d/myvar.sh ; then
+      sudo echo "export MINIKUBE_CPU=4" >> /etc/profile.d/myvar.sh
+    fi
 
   SHELL
   
